version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  frontend:
    image: voice-text-app/frontend:1.0.0
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - BACKEND_TARGET=http://backend:8000
    volumes:
    - ./frontend/:/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    image: voice-text-app/backend:1.0.0
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend/:/app/
    environment:
      - ENV=DEV
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always
